### ISSUE TITLE
Unknown type error in db plugin (pg)

### ISSUE THREAD

**Issue by spigell** [vadv/gopher-lua-libs#1]
Greetings! 
Thank you for your libs.
If I make select query against type timestamp 

```
query:
local result, err = pg:query("SELECT insert_date FROM table WHERE state = 0 LIMIT 1")

parse:
for _, r in pairs(result.rows) do
    for id, column in pairs(result.columns) do
        print(column, r[id])
    end
end
```
```
2019/01/15 18:25:11 [ERROR] unknown type (value: `time.Time{wall:0xfd2b478, ext:63683068860, loc:(*time.Location)(0xc0001d41e0)}`, converted: `time.Time{wall:0xfd2b478, ext:63683068860, loc:(*time.Location)(0xc0001d41e0)}`)


insert_date	nil

```

Is it possible to convent it to right type? 
In typelist of Gopher-lua I did not found type `time`.
Thanks!

**Comment by vadv** [comment]
thx! fixed in master.

now returns in lua unix timestamp (float64), you may convert returned value to date table with `os.date("*t", r[id])`

this link provides some inforamtion about time in lua: https://www.lua.org/pil/22.1.html

**Comment by spigell** [comment]
Thank you for fast reply.
It works now!
