### ISSUE TITLE
Broken ci runs with fresh packages

### ISSUE THREAD

**Issue by spigell** [vadv/gopher-lua-libs#13]
Greetings. Just warning. With recent updates of cbroglie/mustache and go-sql-driver/mysql CI runs is broken. Go modules not working there, because Travis worker clones git repo and put it inside GOPATH and GO111MODULE set to 'auto'. 
```
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;

	ignoring go.mod;

	see 'go help modules'
```

This behavior changed in go 1.13 - https://github.com/golang/go/wiki/Modules#recent-changes

Refered issues:
https://github.com/cbroglie/mustache/issues/36
https://github.com/go-sql-driver/mysql/issues/1040

With next update of this dependencies glua-libs can't be compiled with go < 1.13

**Comment by vadv** [comment]
ci fixed, removed old golang versions
